# use this config file or not (optional)
use: false

# file's extension
extension: md

# sub-folder with files (optional)
folder: files

# chapters sequence, order is important
files:
  - "1"
  - "2"

# resulting file name
output: readme

# ask to overwrite resulting file or not
ask_overwrite: true
